### ISSUE TITLE
node 在创建数据集的时候会有一些不方便

### ISSUE THREAD

**Issue by yh4922** [vincentdchan/PoloDB#16]
我在创建了 数据集之后 调用是没有问题的 
```
db.createCollection('students');
const collection = db.collection('students');
console.log(collection)
```

但是同一段代码在下次运行的时候就会报错
`collection name 'students' already exists`

感觉改成 在 `db.collection('students');`的时候不存在的话自动创建数据集，存在的话直接返回已存在的数据集，这样会更灵活一下

**Comment by vincentdchan** [comment]
嗯，这个确实不太方便，我下个版本把这个改一下，预计这周内

**Comment by vincentdchan** [comment]
npm 包更新到 0.6.0 试试，现在 db.collection() 如果没有的话会自动创建
