### ISSUE TITLE
PoloDB 端口访问错误

### ISSUE THREAD

**Issue by Zhang-Jia-meng** [vincentdchan/PoloDB#19]
请问test_db.py出现以下问题可能原因是：

test_db.py:13 (test_create_collection)
def test_create_collection():
>     db = polodb.Database(DB_PATH)
E     Exception: IOErr: 拒绝访问。 (os error 5)

**Comment by vincentdchan** [comment]
请问是什么系统？

**Comment by Zhang-Jia-meng** [comment]
windows 64




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vincentdchan/PoloDB"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 晚上7:57
收件人:&nbsp;"vincentdchan/PoloDB"<PoloDB@noreply.github.com&gt;;
抄送:&nbsp;"莪侢狠 也枳偍一介女子"<1726185546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vincentdchan/PoloDB] PoloDB 端口访问错误 (#19)





 
请问是什么系统？

**Comment by vincentdchan** [comment]
DB_PATH 这个变量是本地一个可用的路径吗？项目里的 test_db 应该是 `/tmp/test-py.db`，Windows 下你可以改成别的路径，用来储存你的数据

**Comment by Zhang-Jia-meng** [comment]
嗷 我可以了，这个问题解决。感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vincentdchan/PoloDB"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 晚上8:01
收件人:&nbsp;"vincentdchan/PoloDB"<PoloDB@noreply.github.com&gt;;
抄送:&nbsp;"莪侢狠 也枳偍一介女子"<1726185546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vincentdchan/PoloDB] PoloDB 端口访问错误 (#19)





 
DB_PATH 这个变量是本地一个可用的路径吗？项目里的 test_db 应该是 /tmp/test-py.db，Windows 下你可以改成别的路径，用来储存你的数据

**Comment by vincentdchan** [comment]
不客气
