### ISSUE TITLE
Promising project

### ISSUE THREAD

**Issue by zhanghanduo** [vincentdchan/PoloDB#4]
还没有实际测试，不过非常支持
readme里面小小错字
> PoloDB is a embedded JSON-based database.
'a' 可以改成'an'

很多不需要高并行独立进程的简单场景这种数据库就非常实用了，本人很多个人项目用的就是sqlite.
本人并非程序员,只会一些C++/python/js，完全不会搞rust，但是等项目成熟一些可以帮着一起贡献文档啦,可视化啦之类的
PS:感觉可以加入一些CI/CD之类的自动化流程，以后项目更复杂了的话会提高效率

**Comment by vincentdchan** [comment]
感谢，我晚点修一下这个错字

确实应该加上 CI 哈
