### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by peepo5** [vincentdchan/PoloDB#40]
It would be useful to have some examples for this module, such as in an examples/ folder.

**Comment by aprchen** [comment]
应该加些示例，这样上手难度会低一点，还有就是rust 的doc 看着有点吃力，缺乏示例

**Comment by vincentdchan** [comment]
Created a repo: https://github.com/vincentdchan/polodb-docs to enrich the documents. More an more examples will be added in the future.

We have an official website now: https://www.polodb.org/

**Comment by vincentdchan** [comment]
Done: [https://docs.rs/polodb_core/latest/polodb_core/](https://docs.rs/polodb_core/latest/polodb_core/)
