### ISSUE TITLE
In-database versioning

### ISSUE THREAD

**Issue by peepopoggers** [vincentdchan/PoloDB#57]
Is the version of a database specified in the database file itself?

If it does, that is cool. If it does not, it would be nice to have a feature where (at least) the past major version is automatically converted, meaning manual conversion would not have to be a thing.

**Comment by vincentdchan** [comment]
Yes, the version is encoded in the file format.
I guess you are talking about the v1 to v2 conversion.
Theoretically, the conversion can be done automatically.

If there is another update in the future, I will try to convert automatically. Thanks.
